#!/usr/bin/env bash

############################################################################
# Configuration section
############################################################################

############################################################################

# This should always be the first line of code to facilitate debugging
[ -n "$SELF_DEBUG" ] && set -vx

VERSION='0.6'
SELF=$(basename $0)

die() {
	echo "$1" >&2
	exit "${2:-1}"
}

fatal() {
	echo "$SELF: fatal - $1" >&2
	exit "${2:-1}"
}

debug() {
	[ -n "$SELF_DEBUG" ] && echo "$SELF: debug - $@" >&2
}

info() {
	if [ ! -n "$SELF_QUIET" ]; then echo -e "$SELF: info - \033[33;m$@\033[0m" >&2; fi
}

warn() {
	echo -e "$SELF: warn - \033[31;1;m$@\033[0m" >&2
}

# Log an error without exiting. See skills/logging.md.
error() {
	echo -e "$SELF: error - \033[31;1;m$@\033[0m" >&2
}

# dc wraps long output at a column limit with `\`+newline by default
# (Gavin Howard's dc, the macOS default; GNU dc honours the same env
# var). Disable it so parsing dc output never sees stray continuation
# chars (BUG-039).
export DC_LINE_LENGTH=0

# checks if a certain function exists: eg. has command update
has() {
	local KIND=$1
	local NAME=$2

	type -t $KIND:$NAME | grep -q function
}

escape() {
	if test -t 1; then
		xxd -p -c 0
#		cat -v
	else
		cat
	fi
}

# We need to run getops as soon as possible so we catch -d and other
# options that will modify our behaviour.
# Commands are handled at the end of this script.
while getopts "c:dqpt" flag; do
	if [ x"$1" = x'-q' ]; then
		SELF_QUIET=1
	fi
	if [ x"$1" = x'-d' ]; then
		SELF_DEBUG=1
	fi
	if [ x"$1" = x'-p' ]; then
		SELF_PASSPHRASE=1
	fi
	if [ x"$1" = x'-t' ]; then
		SELF_TEST=1
	fi
	shift 1
done

# Read configuration and set defaults if anything's not set
: ${XDG_CONFIG_HOME:="~/.config"}
: ${XDG_CACHE_HOME:="~/.cache"}
: ${XDG_DATA_HOME:="~/.local/var"}
: ${XDG_SHARE_HOME:="$HOME/.local/share"}

[ -n "$SELF_VERBOSE" ] && set -vx

#------------------------------------------------------------------------------
command:help() {
	if [[ $# != 0 ]]; then
		if ! has command $1; then
			echo "'$1' is not an $SELF command"
			echo ""
			echo "please see '$SELF help'"
			exit -1
		elif ! has help $1; then
			echo "No help found for '$1'"
			echo ""
			echo "please see '$SELF help'"
			exit -2
		else
			help:$1
			return 0
		fi
	else
		cat >&2 <<ENDHELP
usage: $SELF <options> <command>

   options:
   -d                     Enable debug output
   -q                     Enable quiet mode
   -p                     Read BIP39 passphrase

   $SELF implements commands for the bip13 - Address Format for 
   pay-to-script-hash.



generic commands:
   help                    print this help message
   help <command>          prints command specific help.
   version                 print the version of $SELF

bip13 (address format for pay-to-script-hash) commands:
   base58-encode [file]    encodes the binary file or stdin to base58
   base58-decode [file]    decodes the base58 file or stdin to binary

ENDHELP
	fi
}

#------------------------------------------------------------------------------
command:version() {
	echo $VERSION
}

# This file requires extended globs to be parsed
shopt -s extglob

#------------------------------------------------------------------------------
command:base58-encode() {
	BASE64=$(basenc --base16 "${1:-/dev/stdin}" -w0)
	debug "base64: $BASE64"
	debug "dc-script: 16i0${BASE64} Ai[58~rd0<x]dsxx+f"

	local base58_chars="123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
	dc -e "16i0${BASE64} Ai[58~rd0<x]dsxx+f" | while read -r; do
		echo -n "${base58_chars:REPLY:1}"
	done
}

#------------------------------------------------------------------------------
command:base58-decode() {
	read -r < "${1:-/dev/stdin}"
	local base58_chars="123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
	if [[ "$REPLY" =~ ^(1*)([$base58_chars]+)$ ]]; then
		dc -e "${BASH_REMATCH[1]//1/0P}
		0${base58_chars//?/ds&1+} 0${BASH_REMATCH[2]//?/ 58*l&+}P" | escape
        else
		return 1
        fi
}

#------------------------------------------------------------------------------
# Command-line processing
if [[ $# == 0 ]]; then
	command:help
	exit 0
fi

#------------------------------------------------------------------------------
# If this is a builtin command, execute it, otherwise fall through
if has command $1; then
	debug "executing command:$1 ${@:2}"
	command:$1 "${@:2}" # array slice skipping first element
	exit $?
else
	exit $?
fi
