#!/usr/bin/env bash

############################################################################
# Configuration section
############################################################################

############################################################################

# This should always be the first line of code to facilitate debugging
[ -n "$SELF_DEBUG" ] && set -vx

VERSION='0.6'
SELF=$(basename $0)

die() {
	echo "$1" >&2
	exit "${2:-1}"
}

fatal() {
	echo "$SELF: fatal - $1" >&2
	exit "${2:-1}"
}

debug() {
	[ -n "$SELF_DEBUG" ] && echo "$SELF: debug - $@" >&2
}

info() {
	if [ ! -n "$SELF_QUIET" ]; then echo -e "$SELF: info - \033[33;m$@\033[0m" >&2; fi
}

warn() {
	echo -e "$SELF: warn - \033[31;1;m$@\033[0m" >&2
}

# Log an error without exiting. See skills/logging.md.
error() {
	echo -e "$SELF: error - \033[31;1;m$@\033[0m" >&2
}

# checks if a certain function exists: eg. has command update
has() {
	local KIND=$1
	local NAME=$2

	type -t $KIND:$NAME | grep -q function
}

escape() {
	if test -t 1; then
		xxd -p -c 0
#		cat -v
	else
		cat
	fi
}

# We need to run getops as soon as possible so we catch -d and other
# options that will modify our behaviour.
# Commands are handled at the end of this script.
while getopts "c:dqpt" flag; do
	if [ x"$1" = x'-q' ]; then
		SELF_QUIET=1
	fi
	if [ x"$1" = x'-d' ]; then
		SELF_DEBUG=1
	fi
	if [ x"$1" = x'-p' ]; then
		SELF_PASSPHRASE=1
	fi
	if [ x"$1" = x'-t' ]; then
		SELF_TEST=1
	fi
	shift 1
done

# Read configuration and set defaults if anything's not set
: ${XDG_CONFIG_HOME:="~/.config"}
: ${XDG_CACHE_HOME:="~/.cache"}
: ${XDG_DATA_HOME:="~/.local/var"}
: ${XDG_SHARE_HOME:="$HOME/.local/share"}

[ -n "$SELF_VERBOSE" ] && set -vx

command:help() {
	if [[ $# != 0 ]]; then
		if ! has command $1; then
			echo "'$1' is not an $SELF command"
			echo ""
			echo "please see '$SELF help'"
			exit -1
		elif ! has help $1; then
			echo "No help found for '$1'"
			echo ""
			echo "please see '$SELF help'"
			exit -2
		else
			help:$1
			return 0
		fi
	else
		cat >&2 <<ENDHELP
usage: $SELF <options> <command>

options:
 -d                     Enable debug output
 -q                     Enable quiet mode

 $SELF implements private key wallet import format (wif) commands

generic commands:
  help                print this help message
  help <command>      prints command specific help.
  version             print the version of $SELF

wif related commands:
  encode [-t][-p]     encodes the key (-t for TESTNET, -p public key)
  decode              decodes the key to stdout

ENDHELP
	fi
}

command:version() {
	echo $VERSION
}

# This file requires extended globs to be parsed
shopt -s extglob

# private key wallet import format (wif) commands
command:encode() {
	while getopts "c:tp" flag; do
		if [ x"$1" = x'-t' ]; then
			local COMMAND_TEST=1
		fi
		if [ x"$1" = x'-p' ]; then
			local COMMAND_PUB=1
		fi
		shift 1
	done
	
	{
		if [ -n "$COMMAND_TEST" ]; then
			printf "\xEF"
		else
			printf "\x80"
		fi
		head -c 32
		if [ -n "$COMMAND_PUB" ]; then
			printf "\x01"
		fi
	} | bitcoin bip13 base58-encode
}

command:decode() {
	bitcoin bip13 base58-decode | tail -c +2 | head -c 32 | if test -t 1; then
	{
		# see https://stackoverflow.com/questions/48101258/how-to-convert-an-ecdsa-key-to-pem-format
		basenc --base16 -d <<< "302E0201010420"
		cat
		basenc --base16 -d <<< "A00706052B8104000A"
	} | openssl ec -inform der 2> /dev/null
	else
		cat
	fi
}

#------------------------------------------------------------------------------
# Command-line processing
if [[ $# == 0 ]]; then
	command:help
	exit 0
fi

#------------------------------------------------------------------------------
# If this is a builtin command, execute it, otherwise fall through
if has command $1; then
	debug "executing command:$1 ${@:2}"
	command:$1 "${@:2}" # array slice skipping first element
	exit $?
elif scripts has $SELF/$1; then
	scripts $SELF/$1 "${@:2}" # array slice skipping first element
	exit $?
else
	command:help
	exit $?
fi
